"""Verification aggregates + design-control export (P5-2, FR-21).

Rolls the run log (P5-1) into the evidence Cole quotes: "N tests across M unique
stomas, all within ±1 mm, average margin X mm" — plus CSV and a formatted PDF shaped
to drop into design-control docs. Also bridges the P2-1 diameter scoreboard into run
records so a fixture sweep can be logged and reported (grows into P5-3 seeding).

    stoma-verification-report --out report                 # from the run log
    stoma-verification-report --from-fixtures ../fixtures  # score + report
"""

from __future__ import annotations

import argparse
import csv
import io
import sys
from dataclasses import dataclass
from pathlib import Path

from ..runlog import RunRecord

CSV_FIELDS = [
    "model_name",
    "reference_point",
    "metric",
    "truth_mm",
    "measured_mm",
    "deviation_mm",
    "abs_deviation_mm",
    "measured_min_mm",
    "truth_min_mm",
    "deviation_min_mm",
    "tolerance_mm",
    "passed",
    "engine",
    "method",
    "created_at",
    "notes",
    "tags",
]


@dataclass
class RunSummary:
    count: int
    unique_models: int
    measured: int  # runs with a caliper truth (deviation known)
    passed: int
    pass_rate: float
    tolerance_mm: float
    mean_abs_dev_mm: float | None
    max_abs_dev_mm: float | None
    avg_margin_mm: float | None  # tolerance − mean|Δ|
    worst_margin_mm: float | None  # tolerance − max|Δ|
    all_within_tolerance: bool


def summarize(runs: list[RunRecord]) -> RunSummary:
    measured = [r for r in runs if r.abs_deviation_mm is not None]
    devs = [r.abs_deviation_mm for r in measured if r.abs_deviation_mm is not None]
    passed = sum(1 for r in measured if r.passed)
    tol = measured[0].tolerance_mm if measured else 1.0
    mean_abs = sum(devs) / len(devs) if devs else None
    max_abs = max(devs) if devs else None
    return RunSummary(
        count=len(runs),
        unique_models=len({r.model_name for r in runs}),
        measured=len(measured),
        passed=passed,
        pass_rate=passed / len(measured) if measured else 0.0,
        tolerance_mm=tol,
        mean_abs_dev_mm=mean_abs,
        max_abs_dev_mm=max_abs,
        avg_margin_mm=(tol - mean_abs) if mean_abs is not None else None,
        worst_margin_mm=(tol - max_abs) if max_abs is not None else None,
        all_within_tolerance=bool(measured) and all(bool(r.passed) for r in measured),
    )


def headline(s: RunSummary) -> str:
    if s.measured == 0:
        return f"{s.count} runs logged across {s.unique_models} models — no caliper truth yet."
    within = "all within" if s.all_within_tolerance else f"{s.passed}/{s.measured} within"
    margin = f" · average margin {s.avg_margin_mm:.2f} mm" if s.avg_margin_mm is not None else ""
    return (
        f"{s.measured} tests across {s.unique_models} unique stomas · "
        f"{within} ±{s.tolerance_mm:g} mm{margin}"
    )


def to_csv(runs: list[RunRecord]) -> str:
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=CSV_FIELDS, extrasaction="ignore")
    w.writeheader()
    for r in runs:
        row = r.model_dump(mode="json")
        tags = (row.get("config") or {}).get("tags") or {}
        row["tags"] = ";".join(f"{k}={v}" for k, v in tags.items())
        w.writerow({k: row.get(k, "") for k in CSV_FIELDS})
    return buf.getvalue()


def _fmt(v: float | None, nd: int = 2) -> str:
    return "-" if v is None else f"{v:.{nd}f}"


# fpdf2's core Helvetica is latin-1 only; map the few unicode glyphs we use.
_PDF_REPL = {"—": "-", "–": "-", "Δ": "D", "≤": "<=", "≥": ">=", "·": "-", "±": "+/-"}


def _t(s: str) -> str:
    for k, v in _PDF_REPL.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "replace").decode("latin-1")


def to_pdf(runs: list[RunRecord], title: str = "Stoma Companion - Verification Report") -> bytes:
    from fpdf import FPDF  # lazy — the `reports` extra

    s = summarize(runs)
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 9, _t(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(110)
    pdf.cell(
        0,
        6,
        _t(f"Tolerance +/-{s.tolerance_mm:g} mm (FR-09).  Generated by Stoma Companion."),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_text_color(0)
    pdf.ln(2)

    # headline + summary stats
    pdf.set_font("Helvetica", "B", 11)
    pdf.multi_cell(0, 6, _t(headline(s)))
    pdf.ln(1)
    pdf.set_font("Helvetica", "", 10)
    stats = [
        ("Runs logged", str(s.count)),
        ("Unique stomas", str(s.unique_models)),
        ("Within tolerance", f"{s.passed}/{s.measured}"),
        ("Mean |deviation|", f"{_fmt(s.mean_abs_dev_mm)} mm"),
        ("Max |deviation|", f"{_fmt(s.max_abs_dev_mm)} mm"),
        ("Worst-case margin", f"{_fmt(s.worst_margin_mm)} mm"),
    ]
    for label, value in stats:
        pdf.cell(50, 6, _t(label))
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, _t(value), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
    pdf.ln(3)

    # per-run table
    cols = [
        ("Model", 42),
        ("Truth", 22),
        ("Measured", 24),
        ("Dev mm", 20),
        ("|Dev|", 18),
        ("Result", 24),
    ]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(235)
    for name, w in cols:
        pdf.cell(w, 7, name, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 9)
    for r in runs:
        cells = [
            r.model_name[:22],
            _fmt(r.truth_mm),
            _fmt(r.measured_mm),
            "-" if r.deviation_mm is None else f"{r.deviation_mm:+.2f}",
            _fmt(r.abs_deviation_mm),
            "-" if r.passed is None else ("PASS" if r.passed else "FAIL"),
        ]
        for (_, w), text in zip(cols, cells, strict=True):
            pdf.cell(w, 6, _t(text), border=1)
        pdf.ln()

    out = pdf.output()
    return bytes(out)


# --- bridge: P2-1 diameter scoreboard → run records ------------------------


def runs_from_scoreboard(board, fixtures_by_name: dict | None = None) -> list[RunRecord]:
    """Turn a P2-1 `Scoreboard` into run records (skips errored fixtures). Pulls
    engine / reference point / config from the fixtures when available."""
    fixtures_by_name = fixtures_by_name or {}
    records: list[RunRecord] = []
    for r in board.results:
        if r.measured_mm is None:
            continue
        fx = fixtures_by_name.get(r.fixture)
        records.append(
            RunRecord.build(
                model_name=r.fixture,
                measured_mm=r.measured_mm,
                truth_mm=r.truth_mm,
                tolerance_mm=board.tolerance_mm,
                metric=r.metric,
                method=r.method,
                engine=(fx.scale.get("engine") if fx else None),
                reference_point=(fx.truth.get("reference_point") if fx else None),
                config=(fx.params if fx else {}),
            )
        )
    return records


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="stoma-verification-report",
        description="Aggregate the verification run log and export CSV + PDF (P5-2).",
    )
    parser.add_argument("--out", default="verification-report", help="output basename (.csv/.pdf)")
    parser.add_argument(
        "--from-fixtures", type=Path, help="score this fixtures dir instead of the run log"
    )
    parser.add_argument("--method", default="baseline", help="method for --from-fixtures")
    parser.add_argument("--tolerance", type=float, default=1.0)
    parser.add_argument("--title", default="Stoma Companion — Verification Report")
    args = parser.parse_args(argv)

    if args.from_fixtures:
        from .fixtures import discover_fixtures
        from .harness import METHODS, run_scoreboard

        fixtures = discover_fixtures(args.from_fixtures)
        board = run_scoreboard(fixtures, METHODS[args.method], tolerance_mm=args.tolerance)
        runs = runs_from_scoreboard(board, {f.name: f for f in fixtures})
    else:
        from ..config import get_settings
        from ..runlog import build_run_store

        runs = build_run_store(get_settings()).list()

    Path(f"{args.out}.csv").write_text(to_csv(runs))
    Path(f"{args.out}.pdf").write_bytes(to_pdf(runs, title=args.title))
    print(headline(summarize(runs)))
    print(f"wrote {args.out}.csv and {args.out}.pdf ({len(runs)} runs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
